# Generated by Django 5.2 on 2025-05-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarSalesPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
